### ISSUE TITLE
Standalone FHIR resource validation

### ISSUE THREAD

**Issue by StephThaoOng** [heathfrankel/inferno-au-core#15]
Hi team, is there a way to easily launch the standalone FHIR resource validation against AU Core? 
Like so:
![tempsnip](https://github.com/heathfrankel/inferno-au-core/assets/36804832/95381d0a-3fd4-4a7f-bb6f-bea4521b0d00)

**Comment by ir4y** [comment]
It is available here http://au-inferno.beda.software/validator/
