### ISSUE TITLE
Issues list

### ISSUE THREAD

**Issue by projkov** [heathfrankel/inferno-au-core#3]
1. [x] Fix problems with the search parameter **patient** (clinical-patient);
2. [x] Fix search paths which include **typeOf**;
3. [x] Decide the presence of Smart App Launch tests;
4. [ ] Fix problems with the search tests related to the **provenance** resource;
5. [x] Fix tests for Observation resources (it does not run);
6. [ ] Fix tests **All must support elements are provided**;
7. [x] Unable to find **discharge-disposition** search parameter for the Encounter resource in packages and default search parameters

**Comment by projkov** [comment]
@ir4y The tests concerning **"revInclude:Provenance:target"** are functioning correctly. The issue lies within the test data itself. Our provenance resources lack 'target' attributes that contain references to the resources being tested. For instance, when executing tests on Patients using patient IDs, there should be corresponding Provenance entries where the 'target' is linked to the specific patient being tested.

We should think about what we need to do in that case.

**Comment by ir4y** [comment]
Then we need to fix the test data @projkov

**Comment by projkov** [comment]
The same thing for the "Fix tests All must support elements are provided" issue. Looks like we don't have full-filled resources on the server, but testing for "must support elements" requires them at least in one resource.

**Comment by projkov** [comment]
> The same thing for the "Fix tests All must support elements are provided" issue. Looks like we don't have full-filled resources on the server, but testing for "must support elements" requires them at least in one resource.

@ir4y 

It is an incorrect statement. To validate "must support extensions" Inferno uses a method where it gets data from the "extension" attribute of the resource. It's incorrect in our case because we have extensions in other attributes too. For example: "_birthDate". I made changes in this method and now it's trying to get extensions from other attributes in the resource. In general, this approach helps to "pass" for a lot of extensions, because now they are correctly recognized. 

But I still have a problem with the extension "_birthDate". When we get resources from the server via "fhir_client" ruby gem, we don't have "_birthDate" attribute in the patient resource. When we get resources via get request this attribute exists. Currently, I'm trying to understand why we can't get full resources via ruby gem. 

P.S. I tried to create a resource manually through the ruby gem with "_birthDate" and I got a resource without this attribute.

**Comment by projkov** [comment]
> > The same thing for the "Fix tests All must support elements are provided" issue. Looks like we don't have full-filled resources on the server, but testing for "must support elements" requires them at least in one resource.
> 
> @ir4y
> 
> It is an incorrect statement. To validate "must support extensions" Inferno uses a method where it gets data from the "extension" attribute of the resource. It's incorrect in our case because we have extensions in other attributes too. For example: "_birthDate". I made changes in this method and now it's trying to get extensions from other attributes in the resource. In general, this approach helps to "pass" for a lot of extensions, because now they are correctly recognized.
> 
> But I still have a problem with the extension "_birthDate". When we get resources from the server via "fhir_client" ruby gem, we don't have "_birthDate" attribute in the patient resource. When we get resources via get request this attribute exists. Currently, I'm trying to understand why we can't get full resources via ruby gem.
> 
> P.S. I tried to create a resource manually through the ruby gem with "_birthDate" and I got a resource without this attribute.

UPD:

I found a way to get full resource data. The method for checking must support extensions is fixed.
