### ISSUE TITLE
Better text descriptions for test scenarios

### ISSUE THREAD

**Issue by ir4y** [heathfrankel/inferno-au-core#4]
The generated test contains some narative information like this
<img width="894" alt="Screenshot 2024-02-08 at 12 43 17" src="https://github.com/heathfrankel/inferno-au-core/assets/1488983/7c432842-e16e-4aa9-b245-4f2b19f70012">
However this information is missing in the generate summary https://github.com/heathfrankel/inferno-au-core/blob/main/lib/au_core_test_kit/generated/v0.3.0/summary.md

Text narrative should be added to the summary.

**Comment by projkov** [comment]
Hello @ir4y 
What do you think about the updated summary?

https://github.com/heathfrankel/inferno-au-core/blob/main/lib/au_core_test_kit/generated/v0.3.0/summary.md
