### ISSUE TITLE
Remove SMART LAUNCH test from AU Core test sute

### ISSUE THREAD

**Issue by ir4y** [heathfrankel/inferno-au-core#7]
Right now you need to choose a type of SMART LAUNCH for AU Core tests:
<img width="1280" alt="Screenshot 2024-02-08 at 12 49 21" src="https://github.com/heathfrankel/inferno-au-core/assets/1488983/bcb6cc58-3fec-48bb-8795-a56815daeb75">

For the first version, we don't need it. The goal of the first version is just to test that all resources and search parameters are supported.

**Comment by projkov** [comment]
@ir4y Smart App launch select was removed. This issue can be closed.
